name: Inspect Image Built In Job

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.latest.outputs.image }}
    steps:
      - uses: actions/checkout@v2
      - name: Create Example Dockerfile
        run: |
          cat <<-DOCKERFILE > Dockerfile
            FROM alpine
          DOCKERFILE
      - name: Build And Publish Image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/example
          tag_with_ref: true
          push: true
      - name: Get Latest Image
        id: latest
        uses: ./
        with:
          repository: docker.pkg.github.com/${{ github.repository }}/example
  inspect:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Inspect Image
        run: |
          docker pull ${{ needs.build.outputs.image }}
          docker image inspect ${{ needs.build.outputs.image }}
